### ISSUE TITLE
Gamefeel: It takes too long to get back into the game after you die

### ISSUE THREAD

**Issue by magicksRampage** [aristotlepenguin/endless-war#73]
There are two main reasons for this:

1. Other players have too much slime, so you can't compete in PvP
2. Capping takes too much slime to do alone without a high level

Suggested fixes:

1. Remove gangster farming, fishing and mining. This way it will be riskier to get big slime and harder to maintain it.
2. Rebalance capping and/or design a new mechanic that allows you to be useful to your gang without needing big slime or teamwork.

**Comment by aristotlepenguin** [comment]
currently, we're in a gamestate where the incentive is to drop slime in the gangbase, and decay caps you at around 7-8 mil. This means you can get back into the game faster than ever. Some would argue the system worked too well, and death feels meaningless. It's a matter of opinion, but marking as resolved
