### ISSUE TITLE
Database calls take too long, cause the websocket to fall behind

### ISSUE THREAD

**Issue by MeatyLearner** [aristotlepenguin/endless-war#85]
Some database calls take too long, causing heartbeats to be blocked and the websocket to fall behind. 
This is makes the bot unable to keep up with discord events, such as new people joining the server, which forces them to !data to update their roles.

**Comment by magicksRampage** [comment]
Do we know which database calls might be responsible?

**Comment by MeatyLearner** [comment]
Mostly queries involving the items table, frequently the ones in setOffAlarms, though sometimes slime decay, dying and kicking players from subzones also take a while. You can check the logs for more details.

**Comment by magicksRampage** [comment]
oh yeah, find_item_all() is a catastrophe, especially if you don't specify a user id. it loads every item that matches the item type individually as an EwItem. this is no longer necessary since the pseudo items returned by the inventory() function already have their item props loaded

**Comment by magicksRampage** [comment]
the kick() methods could also probably be optimized not to pull all living players individually, by filtering for relevant pois in the original sql statement

**Comment by aristotlepenguin** [comment]
frog resolved this quite a bit through the item caching system, marking as resolved
